apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: config-server
    name: config-server
spec:
    replicas: 1
    selector:
        matchLabels:
            app: config-server
    template:
        metadata:
            labels:
                app: config-server
        spec:
            containers:
            - image: nvrs/transaction-mgmt/config-server:0.0.1-SNAPSHOT
              imagePullPolicy: IfNotPresent
              name: config-server
---

apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: service-discovery
    name: service-discovery
spec:
    replicas: 1
    selector:
        matchLabels:
            app: service-discovery
    template:
        metadata:
            labels:
                app: service-discovery
        spec:
            containers:
                - image: nvrs/transaction-mgmt/service-discovery:0.0.1-SNAPSHOT
                  imagePullPolicy: IfNotPresent
                  name: service-discovery
---

apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: api-gateway
    name: api-gateway
spec:
    replicas: 1
    selector:
        matchLabels:
            app: api-gateway
    template:
        metadata:
            labels:
                app: api-gateway
        spec:
            containers:
                - image: nvrs/transaction-mgmt/api-gateway:0.0.1-SNAPSHOT
                  imagePullPolicy: IfNotPresent
                  name: api-gateway
---

apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: authentication-service
    name: authentication-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: authentication-service
    template:
        metadata:
            labels:
                app: authentication-service
        spec:
            containers:
                - image: nvrs/transaction-mgmt/authentication-service:0.0.1-SNAPSHOT
                  imagePullPolicy: IfNotPresent
                  name: authentication-service
---

apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: merchant-service
    name: merchant-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: merchant-service
    template:
        metadata:
            labels:
                app: merchant-service
        spec:
            containers:
                - image: nvrs/transaction-mgmt/merchant:0.0.1-SNAPSHOT
                  imagePullPolicy: IfNotPresent
                  name: merchant-service
---

apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: product-service
    name: product-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: product-service
    template:
        metadata:
            labels:
                app: product-service
        spec:
            containers:
                - image: nvrs/transaction-mgmt/product:0.0.1-SNAPSHOT
                  imagePullPolicy: IfNotPresent
                  name: product-service
---

apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: customer-service
    name: customer-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: customer-service
    template:
        metadata:
            labels:
                app: customer-service
        spec:
            containers:
                - image: nvrs/transaction-mgmt/customer:0.0.1-SNAPSHOT
                  imagePullPolicy: IfNotPresent
                  name: customer-service
---

apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: transaction-service
    name: transaction-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: transaction-service
    template:
        metadata:
            labels:
                app: transaction-service
        spec:
            containers:
                - image: nvrs/transaction-mgmt/transaction:0.0.1-SNAPSHOT
                  imagePullPolicy: IfNotPresent
                  name: transaction-service
---


apiVersion: v1
kind: Service
metadata:
    name: config-service
spec:
    type: NodePort
    selector:
        app: config-server
    ports:
        - protocol: TCP
          port: 8088
          targetPort: 8088

---

apiVersion: v1
kind: Service
metadata:
    name: discovery-service
spec:
    type: NodePort
    selector:
        app: service-discovery
    ports:
        - protocol: TCP
          port: 8761
          targetPort: 8761
          nodePort: 8761

---

apiVersion: v1
kind: Service
metadata:
    name: api-gateway
spec:
    type: NodePort
    selector:
        app: api-gateway
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
---

apiVersion: v1
kind: Service
metadata:
    name: authentication-service
spec:
    type: NodePort
    selector:
        app: authentication-service
    ports:
        - protocol: TCP
          port: 9191
          targetPort: 9191

---

apiVersion: v1
kind: Service
metadata:
    name: merchant-service
spec:
    type: NodePort
    selector:
        app: merchant-service
    ports:
        - protocol: TCP
          port: 9095
          targetPort: 9095

---

apiVersion: v1
kind: Service
metadata:
    name: product-service
spec:
    type: NodePort
    selector:
        app: product-service
    ports:
        - protocol: TCP
          port: 7070
          targetPort: 7070

---

apiVersion: v1
kind: Service
metadata:
    name: customer-service
spec:
    type: NodePort
    selector:
        app: customer-service
    ports:
        - protocol: TCP
          port: 9090
          targetPort: 9090

---

apiVersion: v1
kind: Service
metadata:
    name: transaction-service
spec:
    type: NodePort
    selector:
        app: transaction-service
    ports:
        - protocol: TCP
          port: 6060
          targetPort: 6060